export const siteConfig = {
  name: "Timi Owolabi - Robotics & Machine Learning Researcher",
  authorName: "Timi Owolabi",
  username: "iitimii",
  description:
    "Timi Owolabi - Robotics and machine learning researcher working on reinforcement learning, vision-language-action models, and learning-based control for legged and aerial robots. Explore my research, projects, and open-source work.",
  url: "https://timi-iitimiis-projects.vercel.app",
  links: {
    twitter: "https://x.com/iitiimii",
    github: "https://github.com/iitimii",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
  },
  ogImage: "https://timi-iitimiis-projects.vercel.app/timi.jpg",
  iconIco: "/favicon.ico",
  logoIcon: "/apple-touch-icon.png",
  keywords: [
    "Timi Owolabi",
    "Oluwatimilehin Owolabi",
    "Timilehin Owolabi",
    "Robotics Researcher",
    "Machine Learning Researcher",
    "Reinforcement Learning",
    "Vision-Language-Action Models",
    "Model Predictive Control",
    "Embodied AI",
    "Humanoid Robotics",
    "Quadrotor Swarms",
    "Robot Manipulation",
    "Control Theory",
    "Meta-Learning",
    "Computer Vision",
    "Covenant University",
    "Google Developer Groups on Campus",
    "Oxford Robotics Institute",
    "Electrical Engineering",
    "MuJoCo",
    "ROS 2",
    "PyTorch",
    "JAX",
  ],
};
